package Application;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;

public class App {

    public static void main(String[] args) {


        Address obadasAddress = new Address("st","ct","st",11332);
        Contact obada = new Contact("Obada","Hamadneh",25);
        obada.address = obadasAddress;

        Gson gson = new Gson();

        System.out.println(gson.toJson(obada));
        String jsonContact = "{\"firstName\":\"Alaa\",\"lastName\":\"Baroud\",\"age\":22," +
                "  \"address\": {" +
                "    \"streetAddress\": \"21 2nd Street\"," +
                "    \"city\": \"New York\"," +
                "    \"state\": \"NY\"," +
                "    \"postalCode\": 10021" +
                "  }}";
        Contact contact = gson.fromJson(jsonContact,Contact.class);
      //  System.out.println(contact);


    }
}
