/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Class;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;

public class App {

    public static void main(String[] args) {

        // --------------- Reading from file ---------------

// Method 1
//        File file = new File("unicorns.txt");
//        try {
//            Scanner scanner = new Scanner(file);
//
//            while(scanner.hasNextLine()){
//                System.out.println(scanner.nextLine());
//            }
//        } catch (FileNotFoundException e) {
//            System.out.println("The provided file path/name caused a file not found exception");
//        }

        // Method 2
//        Path path = Paths.get("unicorns.txt");
//        try {
//            List<String> fileLines = Files.readAllLines(path);
//            for(String line : fileLines){
//                System.out.println(line);
//            }
//        } catch (IOException exception){
//            System.out.println("An error occurred while reading from file");
//        }


        // Method 3
//        try {
//            BufferedReader reader = new BufferedReader(new FileReader("unicorns.txt"));
//            Scanner scanner = new Scanner(reader);
//            while (scanner.hasNext()){
//                System.out.println(scanner.next());
//            }
//        } catch (FileNotFoundException exception){
//            System.out.println("The provided file path/name caused a file not found exception");
//        }

        // Method 4
//        Path path = Paths.get("unicorns.txt");
//        try {
//            BufferedReader reader = Files.newBufferedReader(path);
//            String line = reader.readLine();
//            while (line != null){
//                System.out.println(line);
//                line = reader.readLine();
//            }
//        } catch (IOException e) {
//            e.printStackTrace();
//        }

        // --------------- Reading from file ---------------


        // --------------- HashSet ---------------
        // Hashsets don't maintain order in which you add items them
        // Hashsets don't allow duplicates
//        HashSet<Integer> myFirstHashSet = new HashSet<Integer>();
//
//        myFirstHashSet.add(1);
//        myFirstHashSet.add(11);
//        myFirstHashSet.add(8);
//        myFirstHashSet.add(20);
//        myFirstHashSet.add(20);
//        myFirstHashSet.add(20);
//        myFirstHashSet.add(10);
//        myFirstHashSet.add(300);
//
//
////        for(Integer i : myFirstHashSet){
////            System.out.println(i);
////        }
//
//        Iterator iter = myFirstHashSet.iterator();
//
//        while(iter.hasNext()){
//            System.out.println(iter.next());
//        }
//
//        System.out.println(myFirstHashSet);
        // --------------- HashSet ---------------


        // --------------- HashMap ---------------
        // Hashmaps don't maintain insertion order
        // Hashmaps don't allow duplicate keys
        // Every key-value pair is called an Entry
//        HashMap<String,Integer> nameAgeMap = new HashMap<String,Integer>();  // Kay,Value
//        nameAgeMap.put("Mohammad", 25);
//        nameAgeMap.put("Areej", 23);
//        nameAgeMap.put("Hana", 29);
//        nameAgeMap.put("Ahmad", 26);
//        nameAgeMap.put("Yazan", 23);
//        nameAgeMap.put("Ahmad", 24);
//
//
//
//        for(Map.Entry<String,Integer> entry : nameAgeMap.entrySet()){
//            System.out.println("Name: "+entry.getKey() + " Age: "+entry.getValue());
//        }
//
//        for(String name : nameAgeMap.keySet()) {
//            System.out.println(name);
//            System.out.println(nameAgeMap.get(name));
//        }
//        System.out.println(nameAgeMap);



    }
}
